package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
	"time"
)

const atendeURL = "https://apucarana.atende.net/cidadao/acesso/tipo/1/redirect/1"
const dashboardDefault = "https://dashboard-estatistico-integrado.thiagohbernardi.chatgpt.site/api/integrations/atende/processes"
const processaDados = "processaDados"
const impRelatorioFila = "impRelatorioFila"
const getInformacoesDownload = "getInformacoesDownload"
const uploadIDField = "Upload.idArquivo"

type Config struct { DashboardURL string `json:"dashboardUrl"`; ProfileDir string `json:"profileDir"`; DownloadDir string `json:"downloadDir"`; BrowserPath string `json:"browserPath,omitempty"`; Headless bool `json:"headless"`; DebugPort int `json:"debugPort"` }
type syncPayload struct { SourceFile string `json:"sourceFile"`; ReportID string `json:"reportId,omitempty"`; GeneratedAt string `json:"generatedAt"`; Processes []AtendeProcess `json:"processes"` }
type reportMeta struct { UploadID string `json:"Upload.idArquivo"`; Class string `json:"classe"`; Sigla string `json:"sigla"` }

func appDir() string { exe,_:=os.Executable();return filepath.Dir(exe) }
func defaultConfig() Config { base:=filepath.Join(os.Getenv("LOCALAPPDATA"),"IDEPPLAN","AtendeSync");if strings.TrimSpace(os.Getenv("LOCALAPPDATA"))==""{base=filepath.Join(appDir(),"data")};return Config{DashboardURL:dashboardDefault,ProfileDir:filepath.Join(base,"chrome-profile"),DownloadDir:filepath.Join(base,"downloads"),Headless:true,DebugPort:9222} }
func loadConfig(path string)(Config,error){cfg:=defaultConfig();raw,err:=os.ReadFile(path);if errors.Is(err,os.ErrNotExist){b,_:=json.MarshalIndent(cfg,"","  ");_=os.WriteFile(path,b,0600);return cfg,nil};if err!=nil{return cfg,err};if err:=json.Unmarshal(raw,&cfg);err!=nil{return cfg,err};if cfg.DashboardURL==""{cfg.DashboardURL=dashboardDefault};if cfg.DebugPort==0{cfg.DebugPort=9222};return cfg,nil}
func findBrowser(configured string)(string,error){if configured!=""{if _,err:=os.Stat(configured);err==nil{return configured,nil}};candidates:=[]string{};if runtime.GOOS=="windows"{pf:=os.Getenv("ProgramFiles");pfx:=os.Getenv("ProgramFiles(x86)");local:=os.Getenv("LOCALAPPDATA");candidates=[]string{filepath.Join(pf,"Google","Chrome","Application","chrome.exe"),filepath.Join(pfx,"Google","Chrome","Application","chrome.exe"),filepath.Join(local,"Google","Chrome","Application","chrome.exe"),filepath.Join(pf,"Microsoft","Edge","Application","msedge.exe"),filepath.Join(pfx,"Microsoft","Edge","Application","msedge.exe")}}else{candidates=[]string{"google-chrome","chromium","chromium-browser","microsoft-edge"}};for _,c:=range candidates{if strings.Contains(c,string(os.PathSeparator)){if _,err:=os.Stat(c);err==nil{return c,nil}}else if p,err:=exec.LookPath(c);err==nil{return p,nil}};return "",errors.New("Google Chrome ou Microsoft Edge não encontrado")}
func startBrowser(cfg Config,setup bool)(*exec.Cmd,error){browser,err:=findBrowser(cfg.BrowserPath);if err!=nil{return nil,err};_=os.MkdirAll(cfg.ProfileDir,0700);_=os.MkdirAll(cfg.DownloadDir,0700);args:=[]string{fmt.Sprintf("--remote-debugging-port=%d",cfg.DebugPort),"--remote-allow-origins=*","--no-first-run","--no-default-browser-check","--user-data-dir="+cfg.ProfileDir};if cfg.Headless&&!setup{args=append(args,"--headless=new","--disable-gpu")};args=append(args,atendeURL);cmd:=exec.Command(browser,args...);if err:=cmd.Start();err!=nil{return nil,err};return cmd,nil}
func waitCDP(port int)(*wsClient,error){endpoint:=fmt.Sprintf("http://127.0.0.1:%d",port);deadline:=time.Now().Add(25*time.Second);for time.Now().Before(deadline){if ws,err:=discoverPage(endpoint);err==nil{return dialWS(ws)};time.Sleep(400*time.Millisecond)};return nil,errors.New("não foi possível conectar ao navegador")}
func jsString(v string)string{b,_:=json.Marshal(v);return string(b)}
func dateRange()(string,string){now:=time.Now();return fmt.Sprintf("01/01/%04d",now.Year()),now.Format("02/01/2006")}

func emitReport(cdp *wsClient) error {
	start,end:=dateRange()
	expression:=fmt.Sprintf(`(async()=>{const post=async(url,data)=>{const body=new URLSearchParams();Object.entries(data).forEach(([k,v])=>body.set(k,typeof v==='string'?v:JSON.stringify(v)));const r=await fetch(url,{method:'POST',credentials:'include',headers:{'Content-Type':'application/x-www-form-urlencoded; charset=UTF-8'},body:body.toString()});const t=await r.text();if(!r.ok)throw new Error('HTTP '+r.status);if(/cidadao\/acesso|form.*senha/i.test(t))throw new Error('AUTH_REQUIRED');return t;};const autoId=String(Date.now()%%9000000+1000000);const anti=()=>Date.now();const rel={fila:1,tituloRelatorio:'Relatório Estatístico por Centro de Custos - Atual',orgaos:[],unidades:[],centroCustoCodigo:[],finalidade:'1',ordem:'1',parecer:[],situacao:[],dataInicio:%s,dataFinal:%s,codigoAssunto:'131',tipoOrdenacao:'1',agrupadorOutros:'',codigoSubassunto:'1695',codigoRequerente:'',detalharProcesso:'on',agrupadorCentroCusto:'1',codigoCadastroImobiliario:'',relacionarProcesso:'on',codigoUsuarioAbertura:'',portal:0};const baseParam={report:{siscodigo:'16',repcodigo:'13',laytipo:'0',laycodigo:'0',reptipo:'1',lavversao:'0'},rotina:12002,rel,infofiltro:{'Centro de Custo':'Atual'},janelaAutoId:autoId,selecionar:false,selecionar_multipla:false,permiteAcaoSelecionar:false};const chave={tipoRelatorio:'1',codigoSistema:'16',codigoRelatorio:13};await post('/atende.php?aca=107&ajax=t&ajaxPrevent='+anti()+'&processo=montaTela&rot=12002',{frame:'',override:'1',chave,caller:{},parametro:baseParam,autoId,monitor:0,flush:0,versaoSistema:'v2'});await post('/atende.php?aca=107&ajax=t&ajaxPrevent='+anti()+'&processo=getCabecalhoLayout&rot=12002',{chave:{...chave,layoutTipo:'1',layoutCodigo:'1',chaveEmissao:''},caller:null,parametro:{},autoId:1,monitor:0,flush:0,versaoSistema:'v2'});const dados={layout_relatorio:'1.1.1',lote:'',cabecalho:'{"codigo":"1","padrao":"1"}',formato:'xlsx',orientacao_relatorio:'0',fila_impressao:'on',data_agendamento:'',metodo_de_envio:'',salvar_fisicamente:0,janela_sistema:0,assinaDocumento:0,imprime_zebrado:0,quantidade_copias:'1',conf_assina:0,assinante:[]};await post('/atende.php?aca=107&ajax=t&ajaxPrevent='+anti()+'&processo=%s&rot=12002',{chave,caller:{Rotina:null,Acao:0,AutoId:1,exigeCaptcha:false,caminho:null},parametro:baseParam,autoId,monitor:0,flush:0,dados,versaoSistema:'v2'});const queued={...baseParam,report:{siscodigo:'16',repcodigo:'13',laytipo:'1',laycodigo:'1',reptipo:'1',lavversao:'0'},rel:{...rel,fisico:0},aguarda_em_fila:false,layout:{orientacao:'0',formato:'xlsx',enviaEmail:0,enviaWhatsapp:0,push:0,lote:'',cabecalho:{codigo:'1',padrao:'1'},quantidadePaginas:'1'}};await post('/atende.php?aca=107&ajax=t&ajaxPrevent='+anti()+'&processo=%s&rot=12002',{chave:null,caller:null,parametro:queued,autoId:1,monitor:0,flush:0,versaoSistema:'v2'});return 'OK';})()`,jsString(start),jsString(end),processaDados,impRelatorioFila)
	out,err:=cdp.Evaluate(expression);if err!=nil{return err};if out!="OK"{return fmt.Errorf("emissão não confirmada: %s",out)};return nil
}

var reportIDRe=regexp.MustCompile(`"id"\s*:\s*"(WPT[^"]+)"`)
var statusRe=regexp.MustCompile(`"status"\s*:\s*"?(\d+)"?`)
func queueText(cdp *wsClient)(string,error){expression:=`(async()=>{const b=new URLSearchParams();const p={fromGadgetFixo:true,janelaAutoId:'1',selecionar:false,selecionar_multipla:false,permiteAcaoSelecionar:false};Object.entries({frame:'sync_'+Date.now(),override:'1',chave:'{}',caller:'null',parametro:JSON.stringify(p),autoId:'1',monitor:'0',flush:'0',versaoSistema:'v2'}).forEach(([k,v])=>b.set(k,v));const r=await fetch('/atende.php?aca=101&ajax=t&ajaxPrevent='+Date.now()+'&processo=montaTela&rot=12021',{method:'POST',credentials:'include',headers:{'Content-Type':'application/x-www-form-urlencoded; charset=UTF-8'},body:b.toString()});return await r.text();})()`;return cdp.Evaluate(expression)}
func waitReport(cdp *wsClient)(string,error){deadline:=time.Now().Add(2*time.Minute);var last string;for time.Now().Before(deadline){text,err:=queueText(cdp);if err!=nil{last=err.Error();time.Sleep(2*time.Second);continue};m:=reportIDRe.FindStringSubmatch(text);if len(m)>1{id:=m[1];pos:=strings.Index(text,m[0]);window:=text[pos:];if len(window)>2500{window=window[:2500]};st:=statusRe.FindStringSubmatch(window);if len(st)>1{switch st[1]{case"2","3":return id,nil;case"7":return "",errors.New("Atende.Net informou erro ao gerar o relatório")}}};time.Sleep(2*time.Second)};if last!=""{return "",fmt.Errorf("fila não respondeu: %s",last)};return "",errors.New("tempo limite aguardando o relatório")}
func getDownloadInfo(cdp *wsClient,reportID string)(reportMeta,error){expression:=fmt.Sprintf(`(async()=>{const b=new URLSearchParams();b.set('chave','null');b.set('caller','null');b.set('parametro',JSON.stringify({'ReportEmissao.id':%s}));b.set('autoId','1');b.set('monitor','0');b.set('flush','0');b.set('versaoSistema','v2');const r=await fetch('/atende.php?aca=114&ajax=t&ajaxPrevent='+Date.now()+'&processo=%s&rot=12021',{method:'POST',credentials:'include',headers:{'Content-Type':'application/x-www-form-urlencoded; charset=UTF-8'},body:b.toString()});return await r.text();})()`,jsString(reportID),getInformacoesDownload);text,err:=cdp.Evaluate(expression);if err!=nil{return reportMeta{},err};var meta reportMeta;if err:=json.Unmarshal([]byte(text),&meta);err!=nil{return meta,fmt.Errorf("resposta de download inválida: %w",err)};if meta.UploadID==""{return meta,errors.New("Upload.idArquivo não foi retornado")};return meta,nil}
func downloadReport(cdp *wsClient,cfg Config,meta reportMeta)(string,error){_=os.MkdirAll(cfg.DownloadDir,0700);_,err:=cdp.Command("Browser.setDownloadBehavior",map[string]any{"behavior":"allow","downloadPath":cfg.DownloadDir,"eventsEnabled":true});if err!=nil{_,_=cdp.Command("Page.setDownloadBehavior",map[string]any{"behavior":"allow","downloadPath":cfg.DownloadDir})};before:=time.Now().Add(-time.Second);expression:=fmt.Sprintf(`(()=>{if(typeof download_file!=='function')throw new Error('download_file indisponível');download_file(%s,%s,%s);return 'OK';})()`,jsString(meta.UploadID),jsString(meta.Sigla),jsString(meta.Class));if _,err:=cdp.Evaluate(expression);err!=nil{return "",err};deadline:=time.Now().Add(90*time.Second);for time.Now().Before(deadline){entries,_:=os.ReadDir(cfg.DownloadDir);for _,e:=range entries{if e.IsDir()||strings.HasSuffix(strings.ToLower(e.Name()),".crdownload"){continue};p:=filepath.Join(cfg.DownloadDir,e.Name());info,err:=os.Stat(p);if err==nil&&info.ModTime().After(before)&&info.Size()>1000{f,err:=os.Open(p);if err==nil{sig:=make([]byte,4);_,_=io.ReadFull(f,sig);f.Close();if bytes.Equal(sig,[]byte{'P','K',3,4}){return p,nil}}}};time.Sleep(500*time.Millisecond)};return "",errors.New("download do XLSX não foi concluído")}
func postDashboard(cfg Config,token,sourceFile,reportID string,processes []AtendeProcess)error{payload:=syncPayload{SourceFile:filepath.Base(sourceFile),ReportID:reportID,GeneratedAt:time.Now().Format(time.RFC3339),Processes:processes};raw,_:=json.Marshal(payload);req,err:=http.NewRequest(http.MethodPost,cfg.DashboardURL,bytes.NewReader(raw));if err!=nil{return err};req.Header.Set("Content-Type","application/json");req.Header.Set("Authorization","Bearer "+token);client:=&http.Client{Timeout:90*time.Second};resp,err:=client.Do(req);if err!=nil{return err};defer resp.Body.Close();body,_:=io.ReadAll(io.LimitReader(resp.Body,1<<20));if resp.StatusCode<200||resp.StatusCode>=300{return fmt.Errorf("dashboard HTTP %d: %s",resp.StatusCode,strings.TrimSpace(string(body)))};fmt.Printf("Dashboard atualizado: %s\n",strings.TrimSpace(string(body)));return nil}
func setupLogin(cfg Config)error{cfg.Headless=false;cmd,err:=startBrowser(cfg,true);if err!=nil{return err};defer func(){_=cmd.Process.Kill()}();fmt.Println("Faça login no Atende.Net e aguarde a tela principal carregar.");fmt.Println("Depois volte a esta janela e pressione ENTER. A senha não será lida pelo sincronizador.");_,_=bufio.NewReader(os.Stdin).ReadString('\n');fmt.Println("Sessão salva no perfil exclusivo do AtendeSync.");return nil}
func runSync(cfg Config)error{token:=strings.TrimSpace(os.Getenv("ATENDE_SYNC_TOKEN"));if len(token)<24{return errors.New("defina a variável de ambiente ATENDE_SYNC_TOKEN com o mesmo token configurado no dashboard")};cmd,err:=startBrowser(cfg,false);if err!=nil{return err};defer func(){_=cmd.Process.Kill()}();cdp,err:=waitCDP(cfg.DebugPort);if err!=nil{return err};defer cdp.Close();href,err:=cdp.Evaluate("location.href");if err!=nil{return err};if strings.Contains(href,"/cidadao/acesso"){return errors.New("sessão do Atende.Net expirada; execute AtendeSync.exe --setup-login")};fmt.Println("1/5 Emitindo relatório no Atende.Net...");if err:=emitReport(cdp);err!=nil{return err};fmt.Println("2/5 Aguardando fila de relatórios...");reportID,err:=waitReport(cdp);if err!=nil{return err};fmt.Println("3/5 Obtendo arquivo XLSX...");meta,err:=getDownloadInfo(cdp,reportID);if err!=nil{return err};path,err:=downloadReport(cdp,cfg,meta);if err!=nil{return err};fmt.Println("4/5 Consolidando processos...");processes,err:=ParseAtendeXLSX(path);if err!=nil{return err};fmt.Printf("%d processos reconhecidos.\n",len(processes));fmt.Println("5/5 Enviando ao dashboard...");return postDashboard(cfg,token,path,reportID,processes)}
func main(){setup:=flag.Bool("setup-login",false,"abre o navegador para autenticação inicial");configPath:=flag.String("config",filepath.Join(appDir(),"config.json"),"arquivo de configuração");flag.Parse();cfg,err:=loadConfig(*configPath);if err!=nil{fmt.Fprintln(os.Stderr,"Erro de configuração:",err);os.Exit(2)};if *setup{err=setupLogin(cfg)}else{err=runSync(cfg)};if err!=nil{fmt.Fprintln(os.Stderr,"SINCRONIZAÇÃO NÃO CONCLUÍDA:",err);os.Exit(1)};fmt.Println("Sincronização concluída com sucesso.")}
