import { desc, eq, sql } from "drizzle-orm";
import { ensureDashboardSchema, getDb } from "@/db";
import { projectLocations } from "@/db/schema";
import { getRequestUser } from "@/lib/request-user";

export const dynamic = "force-dynamic";
export async function GET(){try{await ensureDashboardSchema();return Response.json({locations:await getDb().select().from(projectLocations).orderBy(desc(projectLocations.updatedAt))});}catch(error){console.error(error);return Response.json({error:"Não foi possível carregar o mapa de projetos."},{status:500});}}
export async function PUT(request:Request){try{const p=await request.json() as Record<string,unknown>;const projectId=typeof p.projectId==="string"?p.projectId.trim().slice(0,240):"";const latitude=Number(p.latitude),longitude=Number(p.longitude),locationLabel=typeof p.locationLabel==="string"?p.locationLabel.trim().slice(0,180):"";if(!projectId||!Number.isFinite(latitude)||latitude< -90||latitude>90||!Number.isFinite(longitude)||longitude< -180||longitude>180)return Response.json({error:"Coordenadas inválidas."},{status:400});await ensureDashboardSchema();const [location]=await getDb().insert(projectLocations).values({projectId,latitude,longitude,locationLabel,updatedBy:getRequestUser(request)}).onConflictDoUpdate({target:projectLocations.projectId,set:{latitude,longitude,locationLabel,updatedBy:getRequestUser(request),updatedAt:sql`CURRENT_TIMESTAMP`}}).returning();return Response.json({location});}catch(error){console.error(error);return Response.json({error:"Não foi possível salvar a localização."},{status:500});}}
export async function DELETE(request:Request){try{const {projectId}=await request.json() as {projectId?:unknown};if(typeof projectId!=="string"||!projectId)return Response.json({error:"Projeto inválido."},{status:400});await ensureDashboardSchema();await getDb().delete(projectLocations).where(eq(projectLocations.projectId,projectId));return Response.json({ok:true});}catch(error){console.error(error);return Response.json({error:"Não foi possível remover a localização."},{status:500});}}
