import { desc, eq, sql } from "drizzle-orm";
import { ensureDashboardSchema, getDb } from "@/db";
import { partyExpenses } from "@/db/schema";
import { getRequestUser } from "@/lib/request-user";
import { isResponsibleName } from "@/lib/responsibles";

export const dynamic = "force-dynamic";
const text = (value:unknown,max:number) => typeof value === "string" ? value.trim().slice(0,max) : "";
function validate(p:Record<string,unknown>){const value={eventName:text(p.eventName,180),expenseDate:text(p.expenseDate,10),description:text(p.description,400),amount:Number(p.amount),paidBy:text(p.paidBy,120),debtor:text(p.debtor,120),creditor:text(p.creditor,120),responsible:text(p.responsible,120),status:text(p.status,20) as "Pendente"|"Quitado",notes:text(p.notes,2000)};if(!value.eventName||!/^\d{4}-\d{2}-\d{2}$/.test(value.expenseDate)||!value.description||!Number.isFinite(value.amount)||value.amount<=0||!value.paidBy||!value.debtor||!value.creditor||!isResponsibleName(value.responsible)||!["Pendente","Quitado"].includes(value.status))return null;return value;}
export async function GET(){try{await ensureDashboardSchema();return Response.json({expenses:await getDb().select().from(partyExpenses).orderBy(desc(partyExpenses.expenseDate),desc(partyExpenses.updatedAt))});}catch(error){console.error(error);return Response.json({error:"Não foi possível carregar o controle das festas."},{status:500});}}
export async function POST(request:Request){try{const value=validate(await request.json() as Record<string,unknown>);if(!value)return Response.json({error:"Revise os campos obrigatórios do gasto."},{status:400});await ensureDashboardSchema();const editor=getRequestUser(request);const [expense]=await getDb().insert(partyExpenses).values({id:crypto.randomUUID(),...value,createdBy:editor,updatedBy:editor}).returning();return Response.json({expense},{status:201});}catch(error){console.error(error);return Response.json({error:"Não foi possível cadastrar o gasto."},{status:500});}}
export async function PUT(request:Request){try{const p=await request.json() as Record<string,unknown>;const id=text(p.id,160);const value=validate(p);if(!id||!value)return Response.json({error:"Revise os campos obrigatórios do gasto."},{status:400});await ensureDashboardSchema();const [expense]=await getDb().update(partyExpenses).set({...value,updatedBy:getRequestUser(request),updatedAt:sql`CURRENT_TIMESTAMP`}).where(eq(partyExpenses.id,id)).returning();return expense?Response.json({expense}):Response.json({error:"Gasto não encontrado."},{status:404});}catch(error){console.error(error);return Response.json({error:"Não foi possível atualizar o gasto."},{status:500});}}
export async function DELETE(request:Request){try{const {id}=await request.json() as {id?:unknown};if(typeof id!=="string"||!id)return Response.json({error:"Gasto inválido."},{status:400});await ensureDashboardSchema();await getDb().delete(partyExpenses).where(eq(partyExpenses.id,id));return Response.json({ok:true});}catch(error){console.error(error);return Response.json({error:"Não foi possível excluir o gasto."},{status:500});}}
