import { eq, sql } from "drizzle-orm";
import { ensureDashboardSchema, getDb, getR2Binding } from "@/db";
import { staffProfiles } from "@/db/schema";
import { getRequestUser } from "@/lib/request-user";
import { isResponsibleName } from "@/lib/responsibles";

export const dynamic="force-dynamic";
const TYPES=["image/png","image/jpeg","application/pdf"];
const safe=(v:string)=>v.replace(/[\u0000-\u001f<>:"/\\|?*]+/g,"-").slice(0,180)||"perfil";
export async function GET(request:Request){try{const url=new URL(request.url),name=url.searchParams.get("name")??"";await ensureDashboardSchema();if(name&&url.searchParams.get("content")==="1"){if(!isResponsibleName(name))return new Response("Servidor inválido.",{status:400});const [record]=await getDb().select().from(staffProfiles).where(eq(staffProfiles.staffName,name));if(!record)return new Response("Perfil não encontrado.",{status:404});const object=await getR2Binding().get(record.r2Key);if(!object)return new Response("Arquivo não encontrado.",{status:404});return new Response(object.body,{headers:{"content-type":record.contentType,"content-disposition":`inline; filename*=UTF-8''${encodeURIComponent(record.fileName)}`,"cache-control":"private, max-age=60"}});}return Response.json({profiles:await getDb().select({staffName:staffProfiles.staffName,fileName:staffProfiles.fileName,contentType:staffProfiles.contentType,fileSize:staffProfiles.fileSize,updatedBy:staffProfiles.updatedBy,createdAt:staffProfiles.createdAt,updatedAt:staffProfiles.updatedAt}).from(staffProfiles)});}catch(error){console.error(error);return Response.json({error:"Não foi possível carregar os perfis."},{status:500});}}
export async function POST(request:Request){try{const form=await request.formData(),file=form.get("file"),staffName=String(form.get("staffName")??"");if(!(file instanceof File)||!isResponsibleName(staffName)||!TYPES.includes(file.type)||!file.size||file.size>8*1024*1024)return Response.json({error:"Envie PNG, JPG ou PDF de até 8 MB."},{status:400});await ensureDashboardSchema();const db=getDb(),[previous]=await db.select().from(staffProfiles).where(eq(staffProfiles.staffName,staffName));const key=`staff/${encodeURIComponent(staffName)}/${crypto.randomUUID()}-${safe(file.name)}`;await getR2Binding().put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type}});const [profile]=await db.insert(staffProfiles).values({staffName,fileName:safe(file.name),contentType:file.type,fileSize:file.size,r2Key:key,updatedBy:getRequestUser(request)}).onConflictDoUpdate({target:staffProfiles.staffName,set:{fileName:safe(file.name),contentType:file.type,fileSize:file.size,r2Key:key,updatedBy:getRequestUser(request),updatedAt:sql`CURRENT_TIMESTAMP`}}).returning();if(previous?.r2Key&&previous.r2Key!==key)await getR2Binding().delete(previous.r2Key);return Response.json({profile:{...profile,r2Key:undefined}});}catch(error){console.error(error);return Response.json({error:"Não foi possível salvar a foto ou PDF."},{status:500});}}
